modLoader="javafml"
loaderVersion="${loader_version}"
license="GPL"
logoFile="icon.png"
credits="Sonic Ether, vlad2305m"
authors="Sonic Ether, vlad2305m, Max Henkel"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://update.maxhenkel.de/neoforge/sound_physics_remastered"
description='''Provides realistic sound attenuation, reverberation, and absorption through blocks.'''
displayTest="IGNORE_ALL_VERSION"
[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cloth_config"
    mandatory=false
    versionRange="[${cloth_config_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="voicechat"
    mandatory=false
    versionRange="[${minecraft_version}-${voicechat_api_version},)"
    ordering="AFTER"
    side="BOTH"
